### ISSUE TITLE
Migrating from Riverpod ConsumerStatefulWidget how to get Ref before BuildContext

### ISSUE THREAD

**Issue by job-dc** [liangxianzhe/creator#20]
Hey,

I am migrating from Riverpod to Creator since I like the simplicity of this package! I encountered one thing that I couldn't find in the docs / another issue, and that is the following:

In Riverpod there is a `ConsumerState` which exposes the ref before the `BuildContext`. How can I accomplish this in Creator? 

```dart
class HomeView extends ConsumerStatefulWidget {
  const HomeView({Key? key}) : super(key: key);

  @override
  HomeViewState createState() => HomeViewState();
}

class HomeViewState extends ConsumerState<HomeView> {
  @override
  void initState() {
    super.initState();
    // "ref" can be used in all life-cycles of a StatefulWidget.
    ref.read(counterProvider);
  }

  @override
  Widget build(BuildContext context) {
    // We can also use "ref" to listen to a provider inside the build method
    final counter = ref.watch(counterProvider);
    return Text('$counter');
  }
}
```
(https://docs-v2.riverpod.dev/docs/concepts/reading#extending-consumerstatefulwidgetconsumerstate-instead-of-statefulwidgetstate)

Thanks for this wonderful package!

**Comment by liangxianzhe** [comment]
Hello! For creator, `ref` is not available in `initState`, but available in `[didChangeDependencies](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html)`. You can do any initial work there (using context.ref). Flutter calls `initState` -> `didChangeDependencies` -> `build` when the stateful widget is created.

That being said. I notice that you can use ref in `initState` in riverpod, because it calls `getElementForInheritedWidgetOfExactType` under the hood. Creator uses `dependOnInheritedWidgetOfExactType`, which gets the benefits that if CreatorGraph is ever being replaced with a new instance, creator will depend on the new instance.

**Comment by liangxianzhe** [comment]
Inside `build`, you can wrap your logic inside a `Watcher` (or use context.ref sometimes, but see the https://github.com/liangxianzhe/creator#whats-the-difference-between-creatorfuturet-vs-emittert)

**Comment by job-dc** [comment]
Awesome, thanks for the swift reply!
